dist: trusty
sudo: required
language: go

install:
  - go get -t -v ./...
  - go build -v -tags sqlite -o tsoda ./soda

before_script:
  - ./tsoda create -e $SODA_DIALECT
  - ./tsoda migrate -e $SODA_DIALECT

script:
  - go test -tags sqlite ./... -v

global_env:
  - MYSQL_USER="travis"
  - MYSQL_PASSWORD=""
  - POSTGRES_PASSWORD=""

.mysql: &mysql
  services:
    - mysql
  addons:
    apt:
      sources:
        - mysql-5.7-trusty
      packages:
        - mysql-server

.postgres: &postgres
  addons:
    postgresql: "9.5"

.cockroach: &cockroach
  services:
    - docker
  before_install:
    - docker pull cockroachdb/cockroach:v1.1.1
    - docker run -d -p 26257:26257 --name=cockroachdb cockroachdb/cockroach:v1.1.1 start --insecure
    - sleep 4 # Wait for cockroach to be online
  after_script:
    - docker rm -f cockroachdb

.crdb210ssl: &crdb210ssl
  before_install:
    - mkdir -p crdb/certs
    - pushd crdb
    - wget -qO- https://binaries.cockroachdb.com/cockroach-v2.1.0.linux-amd64.tgz | tar  zxv
    - mv cockroach-v2.1.0.linux-amd64/cockroach .
    - ./cockroach cert create-ca --certs-dir certs --ca-key key
    - ./cockroach cert create-client root --certs-dir certs --ca-key key
    - ./cockroach cert create-node localhost 127.0.0.1 `hostname -s` `hostname -f` --certs-dir certs --ca-key key
    - ./cockroach start --certs-dir certs --listen-addr localhost --port 26259 --http-port 8089 --background
    - popd

# TODO: MariaDB builds
.mariadb: &mariadb
  addons:
    mariadb: '10.0'

matrix:
  include:
    - dist: trusty
      go: 1.9
      env: SODA_DIALECT="postgres"
      <<: *postgres
    - dist: trusty
      go: "1.10"
      env: SODA_DIALECT="postgres"
      <<: *postgres
    - dist: trusty
      go: "1.10"
      env: SODA_DIALECT="mysql_travis"
      <<: *mysql
    - dist: trusty
      go: "1.10"
      env: SODA_DIALECT="cockroach"
      <<: *cockroach
    - dist: trusty
      go: "1.10"
      env: SODA_DIALECT="cockroach_ssl"
      <<: *crdb210ssl
    - dist: trusty
      go: "1.10"
      env: SODA_DIALECT="sqlite"
    - dist: trusty
      go: "1.11"
      env: SODA_DIALECT="postgres"
      <<: *postgres
    - dist: trusty
      go: "1.11"
      env: SODA_DIALECT="mysql_travis"
      <<: *mysql
    - dist: trusty
      go: "1.11"
      env: SODA_DIALECT="cockroach"
      <<: *cockroach
    - dist: trusty
      go: "1.11"
      env: SODA_DIALECT="cockroach_ssl"
      <<: *crdb210ssl
    - dist: trusty
      go: "1.11"
      env: SODA_DIALECT="sqlite"
    - dist: trusty
      go: "tip"
      env: SODA_DIALECT="postgres"
      <<: *postgres
    - dist: trusty
      go: "tip"
      env: SODA_DIALECT="mysql_travis"
      <<: *mysql
    - dist: trusty
      go: "tip"
      env: SODA_DIALECT="cockroach"
      <<: *cockroach
    - dist: trusty
      go: "tip"
      env: SODA_DIALECT="cockroach_ssl"
      <<: *crdb210ssl
    - dist: trusty
      go: "tip"
      env: SODA_DIALECT="sqlite"
  allow_failures:
    - go: 'tip'
