dist: trusty
sudo: required
language: go

install:
  - go get -t -v ./...
  - go build -v -tags sqlite -o tsoda ./soda

before_script:
  - ./tsoda create -e $SODA_DIALECT
  - ./tsoda migrate -e $SODA_DIALECT

script:
  - go test -tags sqlite ./... -v

global_env:
  - MYSQL_USER="travis"
  - MYSQL_PASSWORD=""
  - POSTGRES_PASSWORD=""

.mysql: &mysql
  services:
    - mysql
  addons:
    apt:
      sources:
        - mysql-5.7-trusty
      packages:
        - mysql-server

.postgres: &postgres
  addons:
    postgresql: "9.5"

# TODO: MariaDB builds
.mariadb: &mariadb
  addons:
    mariadb: '10.0'

matrix:
  include:
    - dist: trusty
      go: 1.9
      env: SODA_DIALECT="postgres"
      <<: *postgres
    - dist: trusty
      go: 1.9
      env: SODA_DIALECT="mysql_travis"
      <<: *mysql
    - dist: trusty
      go: 1.9
      env: SODA_DIALECT="sqlite"
    - dist: trusty
      go: "1.10"
      env: SODA_DIALECT="postgres"
      <<: *postgres
    - dist: trusty
      go: "1.10"
      env: SODA_DIALECT="mysql_travis"
      <<: *mysql
    - dist: trusty
      go: "1.10"
      env: SODA_DIALECT="sqlite"
    - dist: trusty
      go: "1.11"
      env: SODA_DIALECT="postgres"
      <<: *postgres
    - dist: trusty
      go: "1.11"
      env: SODA_DIALECT="mysql_travis"
      <<: *mysql
    - dist: trusty
      go: "1.11"
      env: SODA_DIALECT="sqlite"
    - dist: trusty
      go: "tip"
      env: SODA_DIALECT="postgres"
      <<: *postgres
    - dist: trusty
      go: "tip"
      env: SODA_DIALECT="mysql_travis"
      <<: *mysql
    - dist: trusty
      go: "tip"
      env: SODA_DIALECT="sqlite"
  allow_failures:
    - go: 'tip'
