variables:
  GOBIN:  "$(GOPATH)/bin" # Go binaries path
  GOPATH: "$(system.defaultWorkingDirectory)/gopath" # Go workspace path
  modulePath: "$(GOPATH)/src/github.com/$(build.repository.name)" # Path to the module"s code

jobs:
- job: Linux
  pool:
    vmImage: "ubuntu-16.04"
  strategy:
    matrix:
    # Cockroach
      go 1.13 (off) cockroach:
        go_version: "1.13"
        GO111MODULE: "off"
        SODA_DIALECT: "cockroach"
    # Cockroach SSL
      go 1.13 (off) cockroach SSL:
        go_version: "1.13"
        GO111MODULE: "off"
        SODA_DIALECT: "cockroach_ssl"
  steps:
    - template: azure-tests.yml