mysql:
  dialect: "mysql"
  database: "pop_test"
  host: {{ envOr "MYSQL_HOST" "127.0.0.1"  }}
  port: {{ envOr "MYSQL_PORT" "3306"  }}
  user: {{ envOr "MYSQL_USER"  "root"  }}
  password: {{ envOr "MYSQL_PASSWORD"  "root"  }}

mysql_travis:
  dialect: "mysql"
  database: "pop_test"
  host: {{ envOr "MYSQL_HOST" "127.0.0.1"  }}
  port: {{ envOr "MYSQL_PORT" "3306"  }}
  user: {{ envOr "MYSQL_USER"  "root"  }}
  password: {{ envOr "MYSQL_PASSWORD"  ""  }}

postgres:
  url: "postgres://postgres:postgres@localhost:5432/pop_test?sslmode=disable"
  pool: 25

cockroach:
  # url: "cockroach://root@127.0.0.1:26257/pop_test?application_name=cockroach&sslmode=disable"
  dialect: "cockroach"
  database: "pop_test"
  host: {{ envOr "COCKROACH_HOST" "127.0.0.1"  }}
  port: {{ envOr "COCKROACH_PORT" "26257"  }}
  user: {{ envOr "COCKROACH_USER" "root"  }}
  password: {{ envOr "COCKROACH_PASSWORD" ""  }}

sqlite:
  dialect: "sqlite3"
  database: "./sql_scripts/sqlite/test.sqlite"

