name: Release
on:
  release:
    types:
      - published

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: setup environment
        run: |-
          echo 'GITHUB_TOKEN=${{ secrets.GORELEASER_PAT }}' > .release-env
      - name: run goreleaser
        run: make release
